### STEP 1: IMPORT ALL NECESSARY LIBRARIES

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import f_regression
from sklearn.model_selection import train_test_split
import os

### STEP 2: CREATE DATA FRAME USING PANDAS

In [2]:
df = pd.read_csv(r'C:\Users\user\Desktop\EPHI\DS Training\Data_Sets\Logistic_Regression_Example.csv')
print('shape = ',df.shape)

shape =  (999, 7)


### DISPLAY HEAD DEFAULT OF FIRST FIVE VALUES

In [3]:
df.head()

V137  V212  BORD  B11  M14  V219  B5
0     4    15     8   13    0     8   1
1     4    15     7   11    0     8   1
2     4    15     6   11    0     8   1
3     4    15     5   22    0     8   1
4     4    15     4   33    0     8   1

### Variable Names
  #### V137 == Number of children resident in the household and aged 5 and under.
  #### V212 == Age of the respondent at first birth is calculated from the CMC
  #### BORD == Birth Order
  #### B11 == Preceding birth interval is calculated as the difference in months b
  #### M14 == Number of antenatal visits during the pregnancy
  #### V219 == Total number of living children including current pregnancy
  #### B5 == Child is Alive


In [4]:
x = df.drop(['B5'],axis = 1)
y = df['B5']
print(x)

     V137  V212  BORD  B11  M14  V219
0       4    15     8   13    0     8
1       4    15     7   11    0     8
2       4    15     6   11    0     8
3       4    15     5   22    0     8
4       4    15     4   33    0     8
..    ...   ...   ...  ...  ...   ...
994     2    23     1   24    4     2
995     1    23     1   27    3     2
996     0    17     6   40    4     7
997     0    17     5   16    0     7
998     0    17     4   37    0     7

[999 rows x 6 columns]


In [5]:
P_value = f_regression(x,y)[1]
print(P_value)

[6.34049159e-05 8.33549495e-01 3.15079948e-03 2.09429927e-03
 7.42016100e-04 1.95961017e-01]


In [6]:
reg = LogisticRegression()
reg.fit(x,y)
r2 = reg.score(x,y)
n = 20
p = 5
adjr2 = 1 - ((1-r2)*(n-1)/(n-p-1))
print(adjr2)

0.8451308451308451


In [7]:
VIF = 1/(1-adjr2)
print(VIF)

6.457063711911357


### STEP 3:TRAIN TEST SPLIT

In [8]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, shuffle = 'True')

In [9]:
x_train = np.array(x_train)
x_test = np.array(x_test)
y_train = np.array(y_train)
y_train = y_train.reshape(len(y_train),1)
y_test = np.array(y_test)
y_test = y_test.reshape(len(y_test),1)


## STEP 4: REGRESSION MODEL

In [10]:
logreg = LogisticRegression()

In [11]:
logreg.fit(x,y)

LogisticRegression()

In [12]:
reg.coef_

array([[ 0.36020689, -0.0136889 , -0.20912595,  0.02170732,  0.22373214,
         0.24630081]])

In [13]:
reg.intercept_

array([0.51447952])

## STEP 5: VALIDATION OF THE MODEL

In [14]:
x_test.shape

(200, 6)

In [15]:
for i in range (len(x_test)):   
    xx = logreg.predict([x_test[i,0:6]])
    delta1 = y[i] - xx
    delta = np.sqrt(delta1**2)
    

## STEP 6: PREDICT

In [16]:
logreg.predict([[1,15,5,28,0,8]])

array([1], dtype=int64)