### STEP 1: IMPORT ALL NECESSARY LIBRARIES

In [17]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import f_regression
from sklearn.model_selection import train_test_split
import os

### STEP 2: CREATE DATA FRAME USING PANDAS

In [2]:
df = pd.read_csv(r'C:\Users\user\Desktop\EPHI\DS Training\Data_Sets\Case_Study_for_Logistic_Regression_.csv')
print('shape = ',df.shape)

shape =  (5998, 8)


### DISPLAY HEAD DEFAULT OF FIRST FIVE VALUES

In [3]:
df.head()

V137  V212  BORD  B11  B19  M14  V219  B5
0     4    15     8   13   31    0     8   1
1     4    15     7   11   44    0     8   1
2     4    15     6   11   55    0     8   1
3     4    15     5   22   66    0     8   1
4     4    15     4   33   89    0     8   1

### Variable Names
  #### V137 == Number of children resident in the household and aged 5 and under.
  #### V212 == Age of the respondent at first birth is calculated from the CMC
  #### BORD == Birth Order
  #### B11 == Preceding birth interval is calculated as the difference in months b
  #### M14 == Number of antenatal visits during the pregnancy
  #### V219 == Total number of living children including current pregnancy
  #### B5 == Child is Alive


In [4]:
x = df.drop(['B5','B19'],axis = 1)
y = df['B5']
print(x)

      V137  V212  BORD  B11  M14  V219
0        4    15     8   13    0     8
1        4    15     7   11    0     8
2        4    15     6   11    0     8
3        4    15     5   22    0     8
4        4    15     4   33    0     8
...    ...   ...   ...  ...  ...   ...
5993     2    17     2   35    0     8
5994     2    17     1   10    0     8
5995     2    19     8   38    0     8
5996     2    19     7   54    4     8
5997     2    19     6   20    0     8

[5998 rows x 6 columns]


In [5]:
P_value = f_regression(x,y)[1]
print(P_value)

[2.15924264e-15 7.46419677e-07 2.72657620e-01 2.97976869e-22
 1.15112541e-11 3.50836373e-07]


In [6]:
reg = LogisticRegression()
reg.fit(x,y)
r2 = reg.score(x,y)
n = 20
p = 5
adjr2 = 1 - ((1-r2)*(n-1)/(n-p-1))
print(adjr2)

0.8382198828180822


In [7]:
VIF = 1/(1-adjr2)
print(VIF)

6.181229297018771


### STEP 3:TRAIN TEST SPLIT

In [8]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, shuffle = 'True')

In [9]:
x_train = np.array(x_train)
x_test = np.array(x_test)
y_train = np.array(y_train)
y_train = y_train.reshape(len(y_train),1)
y_test = np.array(y_test)
y_test = y_test.reshape(len(y_test),1)


## STEP 4: REGRESSION MODEL

In [10]:
logreg = LogisticRegression()

In [11]:
logreg.fit(x,y)

LogisticRegression()

In [12]:
reg.coef_

array([[ 0.27201669,  0.06534582, -0.08065974,  0.03144421,  0.08006388,
         0.21138764]])

In [13]:
reg.intercept_

array([-1.28702837])

## STEP 5: VALIDATION OF THE MODEL

In [14]:
x_test.shape

(1200, 6)

In [15]:
for i in range (len(x_test)):   
    xx = logreg.predict([x_test[i,0:6]])
    delta1 = y[i] - xx
    delta = np.sqrt(delta1**2)
    

## STEP 6: PREDICT

In [16]:
logreg.predict([[1,15,5,28,0,8]])

array([1], dtype=int64)