## STEP 1: IMPORT ALL NECESSEARY LIBRARIES 

In [241]:
import pandas as pd
import numpy as np
import seaborn as sns
import statsmodels.api as sm
import os
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import f_regression
import matplotlib.pyplot as plt

## STEP 2: CREATE A DATA FRAME USING PANDAS AND SEE SIZE

In [242]:
df = pd.read_csv(r'C:\Users\user\Desktop\EPHI\DS Training\Data_Sets\Case_study_Multiple_reg.csv')
print('shape = ',df.shape)

shape =  (20, 15)


 DISPLAY HEAD DEFAULT OF FIRST FIVE VALUES

In [243]:
print(df.head())

   No  YEAR  Probable Estimate    ANC  Dummy 1   DPT3  Dummy 2  Measles  \
0   1  2000                110  27.00      NaN  20.70     2.24    26.60   
1   2  2001                140  29.24      NaN  22.94      NaN    28.26   
2   3  2002                146  31.48      NaN  25.18      NaN    29.92   
3   4  2003                121  33.72      NaN  27.42      NaN    31.58   
4   5  2004                107  35.96      NaN  29.66      NaN    33.24   

   Dummy 3   Sati  Dummy 4    Dia  Dummy 5    iws  Dummy 6  
0     1.66  47.40     3.74  21.10     0.82  23.60     7.32  
1      NaN  51.14      NaN  21.92      NaN  30.92      NaN  
2      NaN  54.88      NaN  22.74      NaN  38.24      NaN  
3      NaN  58.62      NaN  23.56      NaN  45.56      NaN  
4      NaN  62.36      NaN  24.38      NaN  52.88      NaN  


## STEP 3:  PREPROCESSING

###    Data Cleaning

In [247]:
df1 = df.drop(['Dummy 1','Dummy 2','Dummy 3','Dummy 4','Dummy 5','Dummy 6'],axis = 1)
print(df1.head)

<bound method NDFrame.head of     No  YEAR  Probable Estimate    ANC   DPT3  Measles    Sati    Dia    iws
0    1  2000                110  27.00  20.70    26.60  47.400  21.10  23.60
1    2  2001                140  29.24  22.94    28.26  51.140  21.92  30.92
2    3  2002                146  31.48  25.18    29.92  54.880  22.74  38.24
3    4  2003                121  33.72  27.42    31.58  58.620  23.56  45.56
4    5  2004                107  35.96  29.66    33.24  62.360  24.38  52.88
5    6  2005                 92  28.00  31.90    34.90  66.100  25.20  60.20
6    7  2006                120  29.00  32.67    38.37  63.667  26.83  58.75
7    8  2007                106  30.00  33.44    41.84  61.234  28.46  57.30
8    9  2008                 93  31.00  34.21    45.31  58.801  30.09  55.85
9   10  2009                102  32.00  34.98    48.78  56.368  31.72  54.40
10  11  2010                 89  33.00  35.75    52.25  53.935  33.35  52.92
11  12  2011                 89  34.00  36.50 

### Feature Selection

 ## P_Value

In [248]:
x = df1.drop(['Probable Estimate','YEAR','No'],axis = 1)
y = df1['Probable Estimate']
print(x)

      ANC   DPT3  Measles    Sati    Dia    iws
0   27.00  20.70    26.60  47.400  21.10  23.60
1   29.24  22.94    28.26  51.140  21.92  30.92
2   31.48  25.18    29.92  54.880  22.74  38.24
3   33.72  27.42    31.58  58.620  23.56  45.56
4   35.96  29.66    33.24  62.360  24.38  52.88
5   28.00  31.90    34.90  66.100  25.20  60.20
6   29.00  32.67    38.37  63.667  26.83  58.75
7   30.00  33.44    41.84  61.234  28.46  57.30
8   31.00  34.21    45.31  58.801  30.09  55.85
9   32.00  34.98    48.78  56.368  31.72  54.40
10  33.00  35.75    52.25  53.935  33.35  52.92
11  34.00  36.50    55.70  51.500  35.00  51.50
12  39.60  39.84    55.42  55.860  36.88  53.62
13  45.20  43.18    55.14  60.220  38.76  55.74
14  50.80  46.52    54.86  64.580  40.64  57.86
15  56.40  49.86    54.58  68.940  42.52  59.98
16  62.00  53.20    54.30  73.300  44.40  62.10
17  65.89  55.80    55.87  73.630  46.60  63.87
18  69.78  58.40    57.44  73.960  48.80  65.64
19  73.60  61.00    59.00  74.300  51.00

In [249]:
from sklearn.feature_selection import f_regression
P_value = f_regression(x,y)[1]
print(P_value)

[1.22289979e-05 3.43302264e-08 2.20331071e-07 1.11830050e-03
 7.93456293e-09 2.18213388e-04]


### MultiCollinearity

### Formula for adjusted R^2
$R_{adj.}^2 = 1-(1-R^2)*\frac{n-1}{n-p-1}$

In [250]:
from sklearn.linear_model import LinearRegression
reg.fit(x,y)
r2 = reg.score(x,y)
n = 20
p = 5
adjr2 = 1 - ((1-r2)*(n-1)/(n-p-1))
print(adjr2)

0.8262593163961944


In [251]:
VIF = 1/(1-adjr2)
print(VIF)

5.755704301707354


## STEP 3:TRAIN TEST SPLIT

In [252]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,shuffle = 'True')

In [253]:
y_train = np.array(y_train)
y_train = y_train.reshape(len(y_train),1)
y_test = np.array(y_test)
y_test = y_test.reshape(len(y_test),1)

## STEP 4: REGRESSION MODEL

In [254]:
reg.coef_

array([   1.06025682,  256.27207054,   37.23890432,  -51.88583711,
       -303.98550996,  -26.96979205])

In [255]:
reg.intercept_

3315.753947288909

## STEP 5: VALIDATION

In [256]:
x_test = np.array(x_test)
y_test = np.array(y_test)
print(x_test)
target = y

[[39.6  39.84 55.42 55.86 36.88 53.62]
 [69.78 58.4  57.44 73.96 48.8  65.64]
 [31.48 25.18 29.92 54.88 22.74 38.24]
 [65.89 55.8  55.87 73.63 46.6  63.87]]


In [258]:
for i in range (len(x_test)):
    xx = x_test[i,0:6]
    delta1 = (reg.predict([xx]) - y_test[i])
    delta = np.sqrt(delta1**2)
    print(delta)

[6.95076703]
[0.76370299]
[21.20049957]
[0.49382087]


## STEP 5: PREDICTION

In [260]:
reg.predict([[39.6, 39.84, 55.42, 55.86,36.88, 53.62 ]])

array([75.95076703])